package fr.stellaronstep.app.feature.goto

internal val constellationFr =
    mapOf(
        "And" to "Andromède", "Ant" to "Machine pneumatique",
        "Aps" to "Oiseau de paradis", "Aql" to "Aigle",
        "Aqr" to "Verseau", "Ara" to "Autel", "Ari" to "Bélier",
        "Aur" to "Cocher", "Boo" to "Bouvier", "Cae" to "Burin",
        "Cam" to "Girafe", "Cnc" to "Cancer", "CVn" to "Chiens de chasse",
        "CMa" to "Grand Chien", "CMi" to "Petit Chien",
        "Cap" to "Capricorne", "Car" to "Carène", "Cas" to "Cassiopée",
        "Cen" to "Centaure", "Cep" to "Céphée", "Cet" to "Baleine",
        "Cha" to "Caméléon", "Cir" to "Compas", "Col" to "Colombe",
        "Com" to "Chevelure de Bérénice", "CrA" to "Couronne australe",
        "CrB" to "Couronne boréale", "Crt" to "Coupe",
        "Cru" to "Croix du Sud", "Crv" to "Corbeau", "Cyg" to "Cygne",
        "Del" to "Dauphin", "Dor" to "Dorade", "Dra" to "Dragon",
        "Equ" to "Petit Cheval", "Eri" to "Éridan", "For" to "Fourneau",
        "Gem" to "Gémeaux", "Gru" to "Grue", "Her" to "Hercule",
        "Hor" to "Horloge", "Hya" to "Hydre", "Hyi" to "Hydre mâle",
        "Ind" to "Indien", "Lac" to "Lézard", "Leo" to "Lion",
        "Lep" to "Lièvre", "Lib" to "Balance", "LMi" to "Petit Lion",
        "Lup" to "Loup", "Lyn" to "Lynx", "Lyr" to "Lyre",
        "Men" to "Table", "Mic" to "Microscope", "Mon" to "Licorne",
        "Mus" to "Mouche", "Nor" to "Règle", "Oct" to "Octant",
        "Oph" to "Ophiuchus", "Ori" to "Orion", "Pav" to "Paon",
        "Peg" to "Pégase", "Per" to "Persée", "Phe" to "Phénix",
        "Pic" to "Peintre", "PsA" to "Poisson austral", "Psc" to "Poissons",
        "Pup" to "Poupe", "Pyx" to "Boussole", "Ret" to "Réticule",
        "Sge" to "Flèche", "Sgr" to "Sagittaire", "Sco" to "Scorpion",
        "Scl" to "Sculpteur", "Sct" to "Écu de Sobieski", "Ser" to "Serpent",
        "Se1" to "Serpent (Tête)", "Se2" to "Serpent (Queue)",
        "Sex" to "Sextant", "Tau" to "Taureau", "Tel" to "Télescope",
        "TrA" to "Triangle austral", "Tri" to "Triangle", "Tuc" to "Toucan",
        "UMa" to "Grande Ourse", "UMi" to "Petite Ourse",
        "Vel" to "Voiles", "Vir" to "Vierge", "Vol" to "Poisson volant",
        "Vul" to "Petit Renard"
    )

internal val allConstellationsFr =
    constellationFr.values.distinct().sorted()

internal val openNgcTypes =
    mapOf(
        "*" to ("star" to "Étoile"),
        "**" to ("star_double" to "Étoile double"),
        "*Ass" to ("cluster_open" to "Association stellaire"),
        "OCl" to ("cluster_open" to "Amas ouvert"),
        "GCl" to ("cluster_globular" to "Amas globulaire"),
        "Cl+N" to ("nebula_diffuse" to "Amas et nébuleuse"),
        "G" to ("galaxy" to "Galaxie"),
        "GPair" to ("galaxy_pair" to "Paire de galaxies"),
        "GTrpl" to ("galaxy_group" to "Triplet de galaxies"),
        "GGroup" to ("galaxy_group" to "Groupe de galaxies"),
        "PN" to ("nebula_planetary" to "Nébuleuse planétaire"),
        "HII" to ("nebula_diffuse" to "Région H II"),
        "DrkN" to ("nebula_dark" to "Nébuleuse obscure"),
        "EmN" to ("nebula_diffuse" to "Nébuleuse en émission"),
        "Neb" to ("nebula_diffuse" to "Nébuleuse"),
        "RfN" to ("nebula_diffuse" to "Nébuleuse par réflexion"),
        "SNR" to ("supernova_remnant" to "Rémanent de supernova"),
        "Nova" to ("star" to "Nova"),
        "Other" to ("unknown" to "Autre objet")
    )

internal val frenchObjectNames =
    mapOf(
        "M1" to "Nébuleuse du Crabe",
        "M3" to "Amas globulaire M3",
        "M4" to "Amas globulaire M4",
        "M6" to "Amas du Papillon",
        "M7" to "Amas de Ptolémée",
        "M8" to "Nébuleuse de la Lagune",
        "M11" to "Amas du Canard sauvage",
        "M13" to "Grand Amas d'Hercule",
        "M16" to "Nébuleuse de l'Aigle",
        "M17" to "Nébuleuse Oméga",
        "M20" to "Nébuleuse Trifide",
        "M22" to "Grand Amas du Sagittaire",
        "M27" to "Nébuleuse de l'Haltère",
        "M31" to "Galaxie d'Andromède",
        "M33" to "Galaxie du Triangle",
        "M35" to "Amas M35",
        "M36" to "Amas du Moulinet",
        "M37" to "Amas M37",
        "M38" to "Amas de l'Étoile de mer",
        "M42" to "Nébuleuse d'Orion",
        "M43" to "Nébuleuse de Mairan",
        "M44" to "Amas de la Crèche",
        "M45" to "Les Pléiades",
        "M51" to "Galaxie du Tourbillon",
        "M57" to "Nébuleuse de la Lyre",
        "M63" to "Galaxie du Tournesol",
        "M64" to "Galaxie de l'Œil noir",
        "M65" to "Galaxie M65",
        "M66" to "Galaxie M66",
        "M74" to "Galaxie Fantôme",
        "M76" to "Petite Nébuleuse de l'Haltère",
        "M77" to "Galaxie de la Baleine",
        "M81" to "Galaxie de Bode",
        "M82" to "Galaxie du Cigare",
        "M83" to "Galaxie du Moulinet austral",
        "M87" to "Galaxie Virgo A",
        "M94" to "Galaxie de l'Œil de crocodile",
        "M97" to "Nébuleuse du Hibou",
        "M101" to "Galaxie du Moulinet",
        "M104" to "Galaxie du Sombrero",
        "NGC 1499" to "Nébuleuse Californie",
        "NGC 2237" to "Nébuleuse de la Rosette",
        "NGC 2392" to "Nébuleuse du Clown",
        "NGC 6543" to "Nébuleuse de l'Œil de Chat",
        "NGC 6888" to "Nébuleuse du Croissant",
        "NGC 6960" to "Petite Dentelle du Cygne",
        "NGC 6992" to "Grande Dentelle du Cygne",
        "NGC 7000" to "Nébuleuse de l'Amérique du Nord",
        "NGC 7293" to "Nébuleuse de l'Hélice",
        "NGC 869" to "Double Amas de Persée",
        "NGC 884" to "Double Amas de Persée"
    )
